name: 'go-staticcheck'
description: 'Run go-staticcheck'
author: 'Conventional Actions'
inputs:
  version:
    required: false
    description: 'version of staticcheck to use'
    default: latest
  output_path:
    required: false
    description: 'output file path'
    default: staticcheck.sarif
  checks:
    required: false
    description: 'comma-separated list of checks to enable'
  format:
    required: false
    default: sarif
    description: "output format (valid choices are 'sarif', 'stylish', 'text' and 'json')"
  tags:
    required: false
    description: 'comma-separated list of build tags'
  package:
    required: false
    default: './...'
    description: 'package to check'
outputs:
  output_path:
    description: 'output file path'
runs:
  using: 'node20'
  pre: 'dist/setup/index.js'
  main: 'dist/main/index.js'
branding:
  icon: check-circle
  color: purple
